### ISSUE TITLE
Are there areas we can be using records?

### ISSUE THREAD

**Issue by jamietanna** [co-cddo/federated-api-model#4]
As we've now got `record`s available for use, there _may_ be cases it makes sense to use them and we should review them.

**Comment by nahteb** [comment]
We can't use records for our data classes as is at the moment because the `jsonSchema2Pojo` plugin we're using can't be used to generate records instead of POJOs.

Jackson 2.12 does have [support for records](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.12) and the version of Spring Boot we're using uses 2.13, so we could implement the deserialisation ourselves. But I'm not sure if that's worth it.

**Comment by jamietanna** [comment]
Agreed - right now it looks like only `MetadataDao` would be a candidate outside of the `jsonSchema2Pojo` objects. But as we're going to be using Spring Data JPA, that won't be possible with `record`s so I'm going to close this :+1:
